services:
  - type: web
    name: justicia-ar-api
    env: python
    region: oregon
    buildCommand: "cd backend && pip install -r requirements.txt && python init_db.py"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
